### PR TITLE
Add a parse_string() function and Configuration method

### PR DESCRIPTION
**Pull request by dlax**

### CODE REVIEW

**Comment by l00ptr** [comment]
rpm packaging is broken. Is it a known issue or a new one ?
```
  /usr/bin/docker pull dalibo/labs-sdk:centos7
  Error response from daemon: pull access denied for dalibo/labs-sdk, repository does not exist or may require 'docker login': denied: requested access to the resource is denied
  Warning: Docker pull failed with exit code 1, back off 7.932 seconds before retry.
```

**Comment by dlax** [comment]
> I guess the "Remove a now unneeded 'type: ignore' " is related to a 
> specific version of mypy >=0.982 ?


Yes.

**Comment by dlax** [comment]
> rpm packaging is broken. Is it a known issue or a new one ?

New it seems; but definitely unrelated to these changes.

(I gave up on maintaining this, for the record.)

**Review by l00ptr — APPROVED** [review]
LGTM

**Review by pgiraud — APPROVED** [review]

**Pull request merged**
